create or replace TABLE HUB_INDIVIDUALGENRE (
	HUB_INDIVIDUALGENRE_HK VARCHAR(32),
	HUB_INDIVIDUALGENRE_BK VARCHAR(32),
	HUB_LOAD_DTS TIMESTAMP_NTZ(9) NOT NULL COMMENT 'Load Time',
	HUB_REC_SRC VARCHAR(50) NOT NULL COMMENT 'Application Source',
   constraint PK_HUB_INDIVIDUALGENRE primary key (HUB_INDIVIDUALGENRE_HK)
) COMMENT = 'The gender of the physical person';
