create or replace TABLE LINK_COLLABORATOR_INDIVIDUAL_CHILD (
	LINK_COLLABORATOR_INDIVIDUAL_CHILD_HK VARCHAR(32),
	LINK_COLLABORATOR_INDIVIDUAL_CHILD_BK VARCHAR(32),
	LINK_LOAD_DTS TIMESTAMP_NTZ(9) NOT NULL COMMENT 'Load Time',
	LINK_REC_SRC VARCHAR(50) NOT NULL COMMENT 'Application Source',
	HUB_COLLABORATOR_HK VARCHAR(32),
	HUB_INDIVIDUAL_HK VARCHAR(32),
   constraint PK_LINK_COLLABORATOR_INDIVIDUAL_CHILD primary key (LINK_COLLABORATOR_INDIVIDUAL_CHILD_HK),
   constraint FK_LINK_COLLABORATOR_INDIVIDUAL_CHILD_HUB_COLLABORATOR foreign key (HUB_COLLABORATOR_HK) references HUB_COLLABORATOR(HUB_COLLABORATOR_HK),
   constraint FK_LINK_COLLABORATOR_INDIVIDUAL_CHILD_HUB_INDIVIDUAL foreign key (HUB_INDIVIDUAL_HK) references HUB_INDIVIDUAL(HUB_INDIVIDUAL_HK)
) COMMENT 'Country label ISO';
