create or replace TABLE LINK_INDIVIDUAL_PARTY_CHILD (
	LINK_INDIVIDUAL_PARTY_CHILD_HK VARCHAR(32),
	LINK_INDIVIDUAL_PARTY_CHILD_BK VARCHAR(32),
	LINK_LOAD_DTS TIMESTAMP_NTZ(9) NOT NULL COMMENT 'Load Time',
	LINK_REC_SRC VARCHAR(50) NOT NULL COMMENT 'Application Source',
	HUB_INDIVIDUAL_HK VARCHAR(32),
	HUB_PARTY_HK VARCHAR(32),
   constraint PK_LINK_INDIVIDUAL_PARTY_CHILD primary key (LINK_INDIVIDUAL_PARTY_CHILD_HK),
   constraint FK_LINK_INDIVIDUAL_PARTY_CHILD_HUB_INDIVIDUAL foreign key (HUB_INDIVIDUAL_HK) references HUB_INDIVIDUAL(HUB_INDIVIDUAL_HK),
   constraint FK_LINK_INDIVIDUAL_PARTY_CHILD_HUB_PARTY foreign key (HUB_PARTY_HK) references HUB_PARTY(HUB_PARTY_HK)
);
