create or replace TABLE SAT_INDIVIDUALGENRE (
   HUB_INDIVIDUALGENRE_HK VARCHAR(32),
   SAT_LOAD_DTS TIMESTAMP_NTZ(9) NOT NULL COMMENT 'Load Time',
   SAT_REC_SRC VARCHAR(50) NOT NULL COMMENT 'Application Source',
   SAT_HASH_DIFF VARCHAR(32) NOT NULL,
   CODE TEXT COMMENT 'Sex code',   LABEL TEXT COMMENT 'Sex label',   constraint PK_SAT_INDIVIDUALGENRE primary key (HUB_INDIVIDUALGENRE_HK, SAT_LOAD_DTS),
   constraint FK_SAT_INDIVIDUALGENRE foreign key (HUB_INDIVIDUALGENRE_HK) references HUB_INDIVIDUALGENRE(HUB_INDIVIDUALGENRE_HK)
);
