create or replace TABLE HUB_COUNTRY (
	HUB_COUNTRY_HK VARCHAR(32),
	HUB_COUNTRY_BK VARCHAR(32),
	HUB_LOAD_DTS TIMESTAMP_NTZ(9) NOT NULL COMMENT 'Load Time',
	HUB_REC_SRC VARCHAR(50) NOT NULL COMMENT 'Application Source',
   constraint PK_HUB_COUNTRY primary key (HUB_COUNTRY_HK)
) COMMENT = 'The country';
