create or replace TABLE HUB_INDIVIDUAL_GENRE (
	HUB_INDIVIDUAL_GENRE_HK VARCHAR(32),
	HUB_INDIVIDUAL_GENRE_BK VARCHAR(32),
	HUB_LOAD_DTS TIMESTAMP_NTZ(9) NOT NULL COMMENT 'Load Time',
	HUB_REC_SRC VARCHAR(50) NOT NULL COMMENT 'Application Source',
   constraint PK_HUB_INDIVIDUAL_GENRE primary key (HUB_INDIVIDUAL_GENRE_HK)
) COMMENT = 'The gender of the physical person';
