create or replace TABLE HUB_CITY (
	HUB_CITY_HK VARCHAR(32),
	HUB_CITY_BK VARCHAR(32),
	HUB_LOAD_DTS TIMESTAMP_NTZ(9) NOT NULL COMMENT 'Load Time',
	HUB_REC_SRC VARCHAR(50) NOT NULL COMMENT 'Application Source',
   constraint PK_HUB_CITY primary key (HUB_CITY_HK)
) COMMENT = 'The city';
