create or replace TABLE LINK_INDIVIDUAL_INDIVIDUALGENRE_INDIVIDUALGENRE (
	LINK_INDIVIDUAL_INDIVIDUALGENRE_INDIVIDUALGENRE_HK VARCHAR(32),
	LINK_INDIVIDUAL_INDIVIDUALGENRE_INDIVIDUALGENRE_BK VARCHAR(32),
	LINK_LOAD_DTS TIMESTAMP_NTZ(9) NOT NULL COMMENT 'Load Time',
	LINK_REC_SRC VARCHAR(50) NOT NULL COMMENT 'Application Source',
	HUB_INDIVIDUAL_HK VARCHAR(32),
	HUB_INDIVIDUAL_GENRE_HK VARCHAR(32),
   constraint PK_LINK_INDIVIDUAL_INDIVIDUALGENRE_INDIVIDUALGENRE primary key (LINK_INDIVIDUAL_INDIVIDUALGENRE_INDIVIDUALGENRE_HK),
   constraint FK_LINK_INDIVIDUAL_INDIVIDUALGENRE_INDIVIDUALGENRE_HUB_INDIVIDUAL foreign key (HUB_INDIVIDUAL_HK) references HUB_INDIVIDUAL(HUB_INDIVIDUAL_HK),
   constraint FK_LINK_INDIVIDUAL_INDIVIDUALGENRE_INDIVIDUALGENRE_HUB_INDIVIDUAL_GENRE foreign key (HUB_INDIVIDUAL_GENRE_HK) references HUB_INDIVIDUAL_GENRE(HUB_INDIVIDUAL_GENRE_HK)
) COMMENT 'Genre of the individual';
