create or replace TABLE LINK_TICKET_COLLABORATOR_SALESPERSON (
	LINK_TICKET_COLLABORATOR_SALESPERSON_HK VARCHAR(32),
	LINK_TICKET_COLLABORATOR_SALESPERSON_BK VARCHAR(32),
	LINK_LOAD_DTS TIMESTAMP_NTZ(9) NOT NULL COMMENT 'Load Time',
	LINK_REC_SRC VARCHAR(50) NOT NULL COMMENT 'Application Source',
	HUB_TICKET_HK VARCHAR(32),
	HUB_COLLABORATOR_HK VARCHAR(32),
   constraint PK_LINK_TICKET_COLLABORATOR_SALESPERSON primary key (LINK_TICKET_COLLABORATOR_SALESPERSON_HK),
   constraint FK_LINK_TICKET_COLLABORATOR_SALESPERSON_HUB_TICKET foreign key (HUB_TICKET_HK) references HUB_TICKET(HUB_TICKET_HK),
   constraint FK_LINK_TICKET_COLLABORATOR_SALESPERSON_HUB_COLLABORATOR foreign key (HUB_COLLABORATOR_HK) references HUB_COLLABORATOR(HUB_COLLABORATOR_HK)
);
