create or replace TABLE LINK_PRODUCTBUYING_PRODUCT_PRODUCT (
	LINK_PRODUCTBUYING_PRODUCT_PRODUCT_HK VARCHAR(32),
	LINK_PRODUCTBUYING_PRODUCT_PRODUCT_BK VARCHAR(32),
	LINK_LOAD_DTS TIMESTAMP_NTZ(9) NOT NULL COMMENT 'Load Time',
	LINK_REC_SRC VARCHAR(50) NOT NULL COMMENT 'Application Source',
	HUB_PRODUCT_BUYING_HK VARCHAR(32),
	HUB_PRODUCT_HK VARCHAR(32),
   constraint PK_LINK_PRODUCTBUYING_PRODUCT_PRODUCT primary key (LINK_PRODUCTBUYING_PRODUCT_PRODUCT_HK),
   constraint FK_LINK_PRODUCTBUYING_PRODUCT_PRODUCT_HUB_PRODUCT_BUYING foreign key (HUB_PRODUCT_BUYING_HK) references HUB_PRODUCT_BUYING(HUB_PRODUCT_BUYING_HK),
   constraint FK_LINK_PRODUCTBUYING_PRODUCT_PRODUCT_HUB_PRODUCT foreign key (HUB_PRODUCT_HK) references HUB_PRODUCT(HUB_PRODUCT_HK)
) COMMENT 'Product purchased';
