create or replace TABLE LINK_TICKET_PRODUCTBUYING_PRODUCTSBUYING (
	LINK_TICKET_PRODUCTBUYING_PRODUCTSBUYING_HK VARCHAR(32),
	LINK_TICKET_PRODUCTBUYING_PRODUCTSBUYING_BK VARCHAR(32),
	LINK_LOAD_DTS TIMESTAMP_NTZ(9) NOT NULL COMMENT 'Load Time',
	LINK_REC_SRC VARCHAR(50) NOT NULL COMMENT 'Application Source',
	HUB_TICKET_HK VARCHAR(32),
	HUB_PRODUCT_BUYING_HK VARCHAR(32),
   constraint PK_LINK_TICKET_PRODUCTBUYING_PRODUCTSBUYING primary key (LINK_TICKET_PRODUCTBUYING_PRODUCTSBUYING_HK),
   constraint FK_LINK_TICKET_PRODUCTBUYING_PRODUCTSBUYING_HUB_TICKET foreign key (HUB_TICKET_HK) references HUB_TICKET(HUB_TICKET_HK),
   constraint FK_LINK_TICKET_PRODUCTBUYING_PRODUCTSBUYING_HUB_PRODUCT_BUYING foreign key (HUB_PRODUCT_BUYING_HK) references HUB_PRODUCT_BUYING(HUB_PRODUCT_BUYING_HK)
) COMMENT 'List of product purchases in the ticket';
