create or replace TABLE SAT_COLLABORATOR (
   HUB_COLLABORATOR_HK VARCHAR(32),
   SAT_LOAD_DTS TIMESTAMP_NTZ(9) NOT NULL COMMENT 'Load Time',
   SAT_REC_SRC VARCHAR(50) NOT NULL COMMENT 'Application Source',
   SAT_HASH_DIFF VARCHAR(32) NOT NULL,
   COLLABORATOR_ID TEXT,
   constraint PK_SAT_COLLABORATOR primary key (HUB_COLLABORATOR_HK, SAT_LOAD_DTS),
   constraint FK_SAT_COLLABORATOR foreign key (HUB_COLLABORATOR_HK) references HUB_COLLABORATOR(HUB_COLLABORATOR_HK)
);
